name: Test Secrets

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret values
        run: |
          echo "Host length: ${#DATABRICKS_HOST}"
          echo "Token length: ${#DATABRICKS_TOKEN}"
          echo "Catalog length: ${#DATABRICKS_CATALOG}"
          echo "HTTP Path length: ${#DATABRICKS_HTTP_PATH}"
          echo "Host value: ***${DATABRICKS_HOST: -4}"
        env:
          DATABRICKS_HOST: ${{ secrets.DBT_DATABRICKS_HOST_NAME }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DBT_DATABRICKS_HTTP_PATH }}
          DATABRICKS_TOKEN: ${{ secrets.DBT_DATABRICKS_TOKEN }}
          DATABRICKS_CATALOG: ${{ secrets.DBT_DATABRICKS_CATALOG }}
