name: Test Secret Value

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check test secret
        run: echo "TEST_SECRET_CHECK length: ${#TEST_VAL}"
        env:
          TEST_VAL: ${{ secrets.TEST_SECRET_CHECK }}
